`qscout` compile
SupertechLabs/cirq-superstaq pull request #101
Opened 2021-10-27 20:09 UTC by vtomole

2021-10-30 21:39 UTC, singular-value commented
Include integration test?

2021-10-30 21:41 UTC, singular-value commented on examples/qscout_compile.ipynb
> +{
<p>QSCOUT</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/SupertechLabs/cirq-superstaq/pull/101/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2021-10-30 21:41 UTC, singular-value requested changes
- Looks like this PR extraneously adds a new file, finance_ouput.ipynb

2021-11-01 00:09 UTC, vtomole commented
> Looks like this PR extraneously adds a new file, finance_ouput.ipynb
Removed.

2021-11-01 00:09 UTC, vtomole commented on examples/qscout_compile.ipynb
> +{
Done.

2021-11-01 00:15 UTC, singular-value reviewed
no other comments from my end

2021-11-01 16:16 UTC, singular-value reviewed
lgtm

2021-11-01 16:17 UTC, vtomole commented
@singular-value Will need official approval to merge.

2021-11-01 16:44 UTC, singular-value approved these changes

2021-11-01 16:48 UTC, merged