add custom Rxy gate
SupertechLabs/cirq-superstaq pull request #138
Opened 2021-12-15 20:46 UTC by perlinm

2021-12-15 21:05 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    circ_B += cirq.rz(-rot_gate.axis_angle).on(qubit)
Ah, it feel strange calling properties like this without going through a getter and setter. @richrines1 thoughts?

2021-12-15 21:07 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    assert "Rxy" in str(rot_gate)
You are asserting only a part of the string to test the string functionality because it's properties are being randomly generated. I suggest you create a deterministic operation just to test this instead.

2021-12-15 21:09 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    assert np.allclose(cirq.unitary(circ_A), cirq.unitary(circ_B))
```suggestion
   circuit = cirq.Circuit(rot_gate.on(qubit))
    
    # build Rxy decomposition manually
    decomposed_circuit = cirq.Circuit(cirq.rz(-rot_gate.axis_angle).on(qubit),
    cirq.rx(rot_gate.rot_angle).on(qubit),
    cirq.rz(+rot_gate.axis_angle).on(qubit)
    )
    
    assert np.allclose(cirq.unitary(circuit), cirq.unitary(decomposed_circuit))
```

2021-12-15 21:13 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        return f"superstaq.cq_device.Rxy({self.axis_angle}, {self.rot_angle})"
It's `cirq_superstaq.custom_gates.Rxy` now.

2021-12-15 21:32 UTC, perlinm commented on cirq_superstaq/custom_gates_test.py
> +    assert "Rxy" in repr(rot_gate)
Yep, fixed (in upcoming commit) :+1:

2021-12-15 21:32 UTC, perlinm commented on cirq_superstaq/custom_gates_test.py
> +def test_Rxy() -> None:
:+1:

2021-12-15 21:33 UTC, perlinm commented on cirq_superstaq/custom_gates.py
> +        return f"superstaq.cq_device.Rxy({self.axis_angle}, {self.rot_angle})"
Yep, missed that when importing.  Thanks.

2021-12-15 21:38 UTC, perlinm commented on cirq_superstaq/custom_gates_test.py
> +    assert "Rxy" in str(rot_gate)
done

2021-12-15 21:40 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        return f"superstaq.cq_device.Rxy({self.axis_angle}, {self.rot_angle})"
I think we've just been doing `cirq_superstaq.Rxy` (relatedly `Rxy` should be imported in `__init__.py`)

2021-12-15 21:42 UTC, richrines1 commented on cirq_superstaq/custom_gates_test.py
> +        np.random.random() * 2 * np.pi, np.random.random() * 2 * np.pi
not sure if it's unreasonable but i feel a little weird about using `random()` in tests

2021-12-15 22:00 UTC, vtomole requested changes

2021-12-15 22:00 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    assert str(circuit) == "0: ───Rxy(π, 0.5π)───"
Replace with [cirq.testing.assert_has_diagram](https://github.com/SupertechLabs/cirq-superstaq/blob/ca98fb68613f40c1264cea13022472824c4ab043/cirq_superstaq/custom_gates_test.py#L126)

2021-12-15 22:00 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    )
This can be moved into the above test as it only really takes 4 lines.
```suggestion
    circuit = cirq.Circuit(
        cirq_superstaq.custom_gates.Rxy(np.pi, 0.5 * np.pi).on(qubit)
    )
```

2021-12-15 22:01 UTC, richrines1 commented on cirq_superstaq/custom_gates_test.py
> +    assert "Rxy" in str(rot_gate)
i feel a little weird about randomized tests.  if there is something that will pass/fail depending on the input, it seems like we should check a bunch of inputs rather than having a test that passes some of the time or fails in non-reproducible ways

2021-12-16 00:53 UTC, vtomole approved these changes
LGTM

2021-12-16 00:59 UTC, merged