Adds `pulser` required module
SupertechLabs/cirq-superstaq pull request #158
Opened 2022-01-18 19:55 UTC by dowusu-antwi

Fixes #157. Adds `pulser` module (and installs correct version of `numpy`). Example notebook requires running `pip install -r pulse-requirements.txt`.

![css-pulser](https://user-images.githubusercontent.com/18367737/150008995-34287cb3-8646-47e2-8ba8-a708a68a62fa.png)

2022-01-18 20:04 UTC, singular-value reviewed
Is the idea that we would add to the README that users who want pulse support should `pip install pulser`?

2022-01-18 20:05 UTC, singular-value commented on examples/neutral_atom_compile.ipynb
> +    "import pulser\n",
would this nb still work without this import?

2022-01-18 20:08 UTC, dowusu-antwi commented on examples/neutral_atom_compile.ipynb
> +    "import pulser\n",
Yes -- fixed.

2022-01-19 22:54 UTC, vtomole requested changes
Change the requirements name to `neutral-atom-requirements.txt`. In the README, what order do we want to have the users run the `requirements.txts` if they want to do neutral atom stuff?

2022-01-19 23:01 UTC, dowusu-antwi commented
> Change the requirements name to `neutral-atom-requirements.txt`. In the README, what order do we want to have the users run the `requirements.txts` if they want to do neutral atom stuff?

Done.

> Change the requirements name to `neutral-atom-requirements.txt`. In the README, what order do we want to have the users run the `requirements.txts` if they want to do neutral atom stuff?

Done (added optional `pip install` for `neutral-atom-requirements`.txt).

2022-01-19 23:16 UTC, vtomole approved these changes
LGTM

2022-01-19 23:16 UTC, merged