`upload_aqt_configs` methods and downgrade python from 3.8 to 3.7
SupertechLabs/cirq-superstaq pull request #19
Opened 2021-08-10 23:23 UTC by vtomole

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/15

2021-08-11 18:00 UTC, singular-value requested changes
Just one request

2021-08-11 18:02 UTC, singular-value commented on cirq_superstaq/service.py
> +        pulses_file.close()
The with block also ensures that the file is closed even if there was an error in the reading
https://realpython.com/read-write-files-python/#:~:text=The%20with%20statement%20automatically%20takes%20care%20of%20closing%20the%20file%20once%20it%20leaves%20the%20with%20block%2C%20even%20in%20cases%20of%20error.%20I%20highly%20recommend%20that%20you%20use%20the%20with%20statement%20as%20much%20as%20possible%2C%20as%20it%20allows%20for%20cleaner%20code%20and%20makes%20handling%20any%20unexpected%20errors%20easier%20for%20you.

2021-08-11 19:56 UTC, vtomole commented on cirq_superstaq/service.py
> +        pulses_file.close()
Done.

2021-08-11 21:06 UTC, singular-value requested changes

2021-08-11 21:06 UTC, singular-value commented on cirq_superstaq/service_test.py
> +    with open("/tmp/Variables.yaml", "w") as pulses_file:
`variables_file` here and next line

2021-08-12 17:01 UTC, vtomole commented on cirq_superstaq/service_test.py
> +    with open("/tmp/Variables.yaml", "w") as pulses_file:
whoops copy paste. Done.

2021-08-12 18:32 UTC, merged