Custom gates updates
SupertechLabs/cirq-superstaq pull request #245
Opened 2022-05-11 22:44 UTC by richrines1

various updates/fixes to `custom_gates`:
* adds `custom_gates.IX` to correct `AQTICCX` diagram
* changes `ParallelRGate`'s QASM string from "GR(..)" to "gr(..)" (the former is used by qiskit's `GR()` gate but isn't valid in OpenQASM 2.0, in which identifiers must begin w/ a lowercase letter)
* modifies `ZZSwapGate._decompose_` so it has the same global phase as `ZZSwapGate._unitary_`
* unrolls `ParallelGates` instances when they're a component of another `ParallelGates`

2022-05-18 16:58 UTC, dowusu-antwi commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
> isn't valid in OpenQASM 2.0, in which identifiers must begin w/ a lowercase letter

Ah nevermind on the first question -- I just saw the above comment on OpenQASM 2.0.

2022-05-18 21:20 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
> (Also, just curious: what was the reasoning behind the `GR` name again?)

mostly for consistency w/ the corresponding qiskit gate `qiskit.circuit.library.GR(num_qubits, theta, phi)`, which produces the qasm string `GR(theta, phi)` (with the capitals). but maybe this reasoning is less good now that we're changing the case?

2022-05-18 21:23 UTC, dowusu-antwi commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
Oh I see -- in that case sticking with `gr` makes sense to me.

2022-05-19 16:25 UTC, vtomole requested changes

2022-05-19 16:25 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +                self.component_gates.append(gate)
Curious: why are we calling `.append` here when we do `+=` in the previous 2 `elif`s?

2022-05-19 16:25 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        return tuple(self.component_gates)
This cast is redundant

```
import cirq
class ParallelGates(cirq.Gate, cirq.InterchangeableQubitsGate):
    def __init__(self, *component_gates: cirq.Gate) -> None:

        self.component_gates = component_gates

        print(type(self.component_gates)) # prints <class 'tuple'>

    def _num_qubits_(self) -> int:
        return len(self.component_gates)


ParallelGates(cirq.X)
```

2022-05-19 16:25 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
If the qasm string that's produced is `GR`, then isn't `gr` an invalid qasm instruction?

2022-05-19 16:45 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
> If the qasm string that's produced is `GR`, then isn't `gr` an invalid qasm instruction?

that's a bug in qiskit - "GR" is not a valid gate name in [openqasm 2](https://arxiv.org/pdf/1707.03429.pdf). qiskit even throws an error when trying to parse it:
```
import qiskit
circuit = qiskit.circuit.library.GR(2, 0.1, 0.2)  # (note GR() outputs a QuantumCircuit, not a Gate)
qasm_str = circuit.qasm()
print(qasm_str)  # prints:
    """
    OPENQASM 2.0;
    include "qelib1.inc";
    gate r(param0,param1) q0 { u3(0.1,-1.3707963,1.3707963) q0; }
    gate GR(0.10, 0.20) q0,q1 { r(0.1,0.2) q0; r(0.1,0.2) q1; }
    qreg q[2];
    GR(0.10, 0.20) q[0],q[1];
    """

_ = qiskit.QuantumCircuit.from_qasm_str(qasm_str)  # raises: "qiskit.qasm.exceptions.QasmError: 'Unable to match any token rule, got -->G<-- Check your OPENQASM source and any include statements.'"

```

2022-05-19 16:53 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
Ah :+1:

2022-05-19 16:54 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +                self.component_gates.append(gate)
in the previous two instances it's adding a list of gates, whereas in the last one it's just appending a single gate. We could also use `component_gates.extend()` for the previous two, or `component_gates += [gate]` for the last one, but it seems like elsewhere we've mostly preferred `+= other_list` and `.append(element)` for lists elsewhere. Which do you think is better? Maybe we should decide on a consistent style for extending lists and add it to the developer guide..

2022-05-19 17:06 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        return tuple(self.component_gates)
`ParallelGates.component_gates` is defined as a list in `__init__`: https://github.com/SupertechLabs/cirq-superstaq/blob/a7d5f420ae3c4c20376c626c13b2883736e13ee7/cirq_superstaq/custom_gates.py#L336

2022-05-19 17:14 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        return tuple(self.component_gates)
Oh, hmm maybe it shouldn't be? Are we doing this because we want our `self.component_gates` to be mutable?

2022-05-19 17:16 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +                self.component_gates.append(gate)
Wasn't aware that the others were doing stuff with lists. This is the simplest style on how to handle this case hence LGTM.

2022-05-19 17:37 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
Filed: https://github.com/Qiskit/qiskit-terra/issues/8090

2022-05-19 21:58 UTC, vtomole submitted a review, later dismissed

2022-05-23 15:38 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
Apparently this was fixed in qiskit-terra 0.19. Is it possible to bump up to that version or will that break qpy?

2022-05-23 17:35 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
we should be able to upgrade the requirement in `qiskit-superstaq` but it will be a breaking change (it means dropping support for qiskit 0.18 entirely, which is currently the only version we allow)

but in light of that change, wdyt this qasm string should be? it looks like the qiskit version is now
```
gate_GR_x_xxx__y_yyy
```
where `xx..` and `yy..` are determined by theta and phi. Ideally we want to avoid the theta/phi dependence so we can use a parametrized qasm gate definition (i.e. `gate_GR(θ,ϕ) q[0], q[1];` vs `gate_GR_θ_ϕ q[0], q[1];`). So we could just use `gate_GR(θ,ϕ)` or keep using `gr(θ,ϕ)`, or alternatively just make this `"parallel_rgate(theta, phi)"` given that we kind of break from the qiskit string either way...

2022-05-23 18:07 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
> Ideally we want to avoid the theta/phi dependence so we can use a parametrized qasm gate definition

What do we really lose by not avoiding the theta/phi dependence?

2022-05-23 18:20 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
basically just that we'd need a new definition for each unique `(theta, phi)` pair, e.g.
```
OPENQASM 2.0;
include "qelib1.inc";

gate r(theta,phi) q0 { u3(0.1,phi-π/2,π/2-phi) q0; }
gate gate_GR_0_10__0_10_ q0,q1 { r(0.1,0.1) q0; r(0.1,0.1) q1; }
gate gate_GR_0_10__0_20_ q0,q1 { r(0.1,0.2) q0; r(0.1,0.2) q1; }
gate gate_GR_0_20__0_10_ q0,q1 { r(0.2,0.1) q0; r(0.2,0.1) q1; }
...

gate_GR_0_10__0_10_ q[0],q[1];
gate_GR_0_10__0_20_ q[0],q[1];
gate_GR_0_20__0_10_ q[0],q[1];
...
```
vs. just
```
OPENQASM 2.0;
include "qelib1.inc";

gate r(theta,phi) q0 { u3(0.1,phi-π/2,π/2-phi) q0; }
gate gate_GR(theta,phi) q0,q1 { r(theta,phi) q0; r(theta,phi) q1; }

gate_GR(0.1,0.1) q[0],q[1];
gate_GR(0.1,0.2) q[0],q[1];
gate_GR(0.2,0.1) q[0],q[1];
...
```
if we can use a parameterized gate definition

2022-05-23 19:58 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
I see. Yeah i prefer not defining each unique situation. Let's use `gate_GR(θ,ϕ)` to make it at least half-consistent with what qiskit has.

2022-05-24 20:40 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        gate_str = "gr({0:half_turns},{1:half_turns})"
done

2022-05-25 17:13 UTC, vtomole approved these changes

2022-05-25 17:14 UTC, merged