Changing every instance of `import cirq_superstaq`  to `import cirq_superstaq as css`
SupertechLabs/cirq-superstaq pull request #248
Opened 2022-05-18 16:16 UTC by pgoiporia

2022-05-19 15:55 UTC, vtomole requested changes
`sampler.py` still contains `import cirq_superstaq`

2022-05-19 19:45 UTC, stephanielee9 commented
Wrapper, notebook, readme should have `css`

2022-05-19 21:44 UTC, vtomole requested changes
All the docstrings should have `css` as well.

2022-05-20 20:25 UTC, vtomole approved these changes

2022-05-22 23:35 UTC, merged