Adding notebook tests
SupertechLabs/cirq-superstaq pull request #249
Opened 2022-05-18 17:55 UTC by pgoiporia

2022-05-21 20:21 UTC, singular-value commented
(notebook test is failing)

2022-05-27 16:25 UTC, vtomole requested changes

2022-05-27 16:25 UTC, vtomole commented on examples/aqt_compile.ipynb
> +    "token = os.getenv(\"SUPERSTAQ_API_KEY\")\n",
You can remove this line and just call `service = css.Service()` on the following line.

2022-05-27 22:33 UTC, pgoiporia commented on examples/aqt_compile.ipynb
> +    "token = os.getenv(\"SUPERSTAQ_API_KEY\")\n",
By line you mean line 30?

2022-05-27 22:35 UTC, vtomole commented on examples/aqt_compile.ipynb
> +    "token = os.getenv(\"SUPERSTAQ_API_KEY\")\n",
Yeah, i think removing like 30 and calling `service = css.Service()` will pass notebooktests

2022-07-08 16:50 UTC, vtomole commented
@pgoiporia Are we ready to update these notebook tests to use the code from `app_ss` now?

2022-07-08 20:37 UTC, pgoiporia commented
@vtomole I can't tell my pytest is failing. It passes locally

2022-07-18 18:36 UTC, vtomole commented on check/pytest_.py
> +
Delete this.

2022-07-18 18:37 UTC, vtomole commented
Resolve merge conflicts as well

2022-08-10 17:38 UTC, stephanielee9 commented
Not relevant anymore

2022-08-10 17:38 UTC, closed without merging