Creating new subfolder ops to simplify construction of custom gates
SupertechLabs/cirq-superstaq pull request #272
Opened 2022-06-17 19:43 UTC by pgoiporia

I've added code for simplifying barrier construction, but if we like this structure, we can apply it to other custom gates as well.
Fixes #260

2022-06-17 19:48 UTC, pgoiporia commented
Not quite sure how to fix the type check. It's passing locally

2022-06-17 21:08 UTC, pgoiporia commented
@singular-value I spoke to @vtomole about the ops folder and he seemed to disagree. How shall we proceed? This branch has commits for both versions

2022-06-17 21:53 UTC, singular-value commented
Yeah it's a significant departure from our current design and worth discussing.

Can you message us about it on Tuesday?

2022-06-17 21:58 UTC, pgoiporia commented
> Yeah it's a significant departure from our current design and worth discussing.
> 
> Can you message us about it on Tuesday?

Will do

2022-06-17 22:05 UTC, vtomole requested changes
Replace everywhere we call  `css.Barrier` with `css.barrier`.

2022-06-17 22:38 UTC, pgoiporia commented
> Replace everywhere we call `css.Barrier` with `css.barrier`.

This would be in SuperstaQ though, right? Because I believe barrier is only defined in css, not used in it.

2022-06-17 22:44 UTC, vtomole commented
Ah sure, yeah, i'm fine with this being a convenience function.

2022-06-17 22:45 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    # Testing barrier functions
Remove comment. What the test doesn't is very clear.

2022-06-17 22:50 UTC, pgoiporia commented
> Ah sure, yeah, i'm fine with this being a convenience function.

Will need to merge this in before I can make changes in SuperstaQ

2022-06-23 02:58 UTC, vtomole commented
> Creating new subfolder ops to simplify construction of custom gates

Discussed IRL with @singular-value and @pgoiporia. For awareness:  current concensus is to leave things as -s given that the size of `custom_gates.py` is not overwhelming yet and that the only packages that follow this pattern are `cirq-core` and `cirq-google`. 

We've also decided to maintain the flat structure than[ kept things simple](https://en.wikipedia.org/wiki/KISS_principle) in our internal codebase until the amount of code started to become unmaintainable. 

This is something we'll re-visit down the road with the growth of `qss` and `css`.

2022-06-23 03:00 UTC, vtomole approved these changes
LGTM

2022-06-23 04:41 UTC, merged

2022-07-11 18:25 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +def barrier(qubits: Sequence[cirq.Qid]) -> cirq.Operation:
@pgoiporia @vtomole out of curiosity why did we decide to make this take a sequence, as opposed to `barrier(*qubits: cirq.Qid)`? it's a bit inconsistent with the rest of `cirq`, e.g.:

```
_ = cirq.measure(q0, q1, q2)  # ok
_ = css.barrier(q0, q1, q2)  # error

_ = cirq.measure([q0, q1, q2])  # error
_ = css.barrier([q0, q1, q2])  # ok
```

2022-07-11 19:32 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +def barrier(qubits: Sequence[cirq.Qid]) -> cirq.Operation:
I overlooked this in review. @pgoiporia Please add a follow up PR that fixes this.