Add resource_estimate integration test
SupertechLabs/cirq-superstaq pull request #304
Opened 2022-07-19 06:48 UTC by paaige

2022-07-19 21:50 UTC, singular-value requested changes
couple comments, also still failing tests

2022-07-19 21:50 UTC, singular-value commented on cirq_superstaq/daily_integration_test.py
> +from applications_superstaq import ResourceEstimate
alphabetize and merge

2022-07-19 21:50 UTC, singular-value commented on cirq_superstaq/daily_integration_test.py
> +    circuit2 = cirq.Circuit(cirq.H(q2), cirq.CZ(q2, q3), cirq.CNOT(q2, q3), cirq.measure(q3))
use the same circuit as in qss? In particular, CNOT first, then CZ.

also, why not stick with q0 and q1?

2022-07-19 21:51 UTC, singular-value commented
The checks seem to be related to the release of a new cirq version and the deprecation of some previous cirq features.

2022-07-25 02:29 UTC, singular-value approved these changes
lgtm, please check locally before deploying.

2022-07-29 15:36 UTC, vtomole approved these changes

2022-07-29 18:16 UTC, merged