Integrate gpu simulator as service
SupertechLabs/cirq-superstaq pull request #312
Opened 2022-07-28 08:39 UTC by paaige

2022-07-29 20:10 UTC, vtomole commented on cirq_superstaq/service.py
> +        amplitudes = self._client.simulate(request_json)
Open a draft PR in gss for this method.

2022-08-24 17:23 UTC, vtomole requested changes

2022-08-24 17:23 UTC, vtomole commented on cirq_superstaq/service.py
> +    def simulate(
We've decided to get rid of this function in place of passing in `method` and `options` arguments to `create_job`

2022-08-24 20:13 UTC, paaige commented on cirq_superstaq/service.py
> +    def simulate(
that's from a very old commit

2022-08-25 15:38 UTC, vtomole commented on cirq_superstaq/service.py
> +            options={"options": json.dumps(options)},
Link

2022-08-25 16:45 UTC, vtomole reviewed
Need to pass checks.

2022-08-25 19:32 UTC, vtomole requested changes
Add tests for this `method` and `serialized_options` arguments.

2022-08-25 19:32 UTC, vtomole commented
After that this should be good to go.

2022-08-25 20:47 UTC, vtomole approved these changes
LGTM

2022-08-25 21:18 UTC, vtomole approved these changes
LGTM!

2022-08-25 21:22 UTC, merged