Make css.Barrier._has_unitary_() return False
SupertechLabs/cirq-superstaq pull request #315
Opened 2022-08-02 21:28 UTC by SalahedeenIssa

Fixes #314

2022-08-03 01:42 UTC, vtomole requested changes
Add test

2022-08-03 01:42 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        print('yes')
Remove debug print

2022-08-03 18:43 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    assert not gate._has_unitary_()
Do `assert not cirq.has_unitary(gate)`

2022-08-04 19:16 UTC, vtomole submitted a review, later dismissed
LGTM

2022-08-05 20:56 UTC, perlinm commented
This possibly introduces more problems than it solves.  Tentatively closing and filing [ss#1520](https://github.com/SupertechLabs/SuperstaQ/issues/1520)

2022-08-05 20:56 UTC, closed without merging