Updating docstrings to prevent indentation errors in sphinx
SupertechLabs/cirq-superstaq pull request #370
Opened 2022-10-26 19:09 UTC by stephanielee9

2022-11-01 15:37 UTC, pgoiporia commented
Sorry I haven't been able to get to this yet! Tagging myself so that I remember to review later today. @pgoiporia

2022-11-01 17:41 UTC, pgoiporia requested changes
Nice work! Just a couple of quick fixes.
I'm assuming you've made these changes to fix something in docs-superstaq. Have you tested whether they work?

2022-11-01 17:41 UTC, pgoiporia commented on cirq_superstaq/service.py
> +                pulse sequence corresponding to the cirq.Circuits and the .pulse_lists attribute is
I believe we use spaces over tabs
```suggestion
                pulse sequence corresponding to the cirq.Circuits and the .pulse_lists attribute is
```

2022-11-01 17:41 UTC, pgoiporia commented on cirq_superstaq/service.py
> +                pulse sequence corresponding to the cirq.Circuits and the .pulse_lists attribute is
I don't know if github detects the change I suggested (I replaced the tab with 4 spaces). If not, you can just change it locally.

2022-11-01 17:41 UTC, pgoiporia commented on cirq_superstaq/service.py
> +                the list(s) of cycles.
Same as above

2022-11-01 17:41 UTC, pgoiporia commented on cirq_superstaq/custom_gates.py
> +        qubits between identical but nonadjacent gates, e.g.::
Not a mistake just something I'm curious about. What exactly does :: denote. Is it for code blocks or for general indentation? Or something else entirely.

2022-11-02 16:07 UTC, stephanielee9 commented on cirq_superstaq/custom_gates.py
> +        qubits between identical but nonadjacent gates, e.g.::
Yep! `::` is for code blocks in reStructuredText

2022-11-02 16:07 UTC, stephanielee9 commented
> Have you tested whether they work?

Yep! I rebuilt the docs in docs-superstaq and these changes removed the errors for me

2022-11-02 16:38 UTC, pgoiporia commented on cirq_superstaq/service.py
> +                pulse sequence corresponding to the cirq.Circuits and the .pulse_lists attribute is
@vtomole looks like this file uses tabs, but when Stephanie changes it to spaces, git doesn't see any diff

2022-11-03 17:42 UTC, pgoiporia commented
> > Have you tested whether they work?
> 
> Yep! I rebuilt the docs in docs-superstaq and these changes removed the errors for me

Awesome! lgtm!

2022-11-03 17:42 UTC, pgoiporia approved these changes

2022-11-03 20:25 UTC, merged