Caching Github Actions
SupertechLabs/cirq-superstaq pull request #405
Opened 2023-01-06 20:29 UTC by pgoiporia

2023-01-06 20:37 UTC, pgoiporia commented
About 2x speedup

2023-01-08 02:33 UTC, vtomole approved these changes
Yep, this is noticeable in the Windows check (10 mins -> 3 mins). Very kewl!

2023-01-09 16:45 UTC, vtomole requested changes
Look at how Cirq caches the Windows checks.

2023-01-11 18:14 UTC, vtomole requested changes
Add windows tests

2023-02-08 22:22 UTC, vtomole approved these changes
LGTM

2023-02-08 22:29 UTC, vtomole approved these changes
LGTM

2023-02-08 22:35 UTC, merged

2023-02-16 19:03 UTC, richrines1 commented on .github/workflows/ci.yml
> +          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
@pgoiporia @vtomole @dowusu-antwi i just noticed that we're not including `requirements.txt` here - should we be? /could this be causing some of the weird behavior we noticed before?

2023-02-16 19:09 UTC, dowusu-antwi commented on .github/workflows/ci.yml
> +          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
> i just noticed that we're not including `requirements.txt` here - should we be?

I think so, but I'll let Palash weigh in to confim.

> could this be causing some of the weird behavior we noticed before?

This could be related, but it was a server-side issue and we include `requirements.txt` in the SuperstaQ `yaml`.

2023-02-16 20:58 UTC, richrines1 commented on .github/workflows/ci.yml
> +          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
fixed in #1358 - it looks like hashFiles accepts multiple files/wildcards, so we can just use `*requirements.txt` to make sure we're including all requirements