`ZXPowGate`, `CR`, `CR45P`, `CR45N`
SupertechLabs/cirq-superstaq pull request #41
Opened 2021-08-30 17:50 UTC by vtomole

2021-08-30 18:06 UTC, singular-value reviewed
Can you also bring in aceCR, aceCRPlusMinus, and aceCRMinusPlus?

2021-08-30 18:15 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +            return f"(ss.parity_gates.ZX**{cirq._compat.proper_repr(self._exponent)})"
```suggestion
            return f"(cirq_superstaq.parity_gates.ZX**{cirq._compat.proper_repr(self._exponent)})"
```

2021-08-30 18:15 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +                return "ss.parity_gates.ZX"
```suggestion
                return "cirq_superstaq.parity_gates.ZX"
```

2021-08-30 18:15 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +            f"ss.parity_gates.ZXPowGate(exponent={cirq._compat.proper_repr(self._exponent)},"
```suggestion
            f"cirq_superstaq.parity_gates.ZXPowGate(exponent={cirq._compat.proper_repr(self._exponent)},"
```

2021-08-30 18:15 UTC, richrines1 commented on cirq_superstaq/custom_gates_test.py
> +    assert repr(cirq_superstaq.ZXPowGate(exponent=0.5)) == "(ss.parity_gates.ZX**0.5)"
```suggestion
    assert repr(cirq_superstaq.ZXPowGate(exponent=0.5)) == "(cirq_superstaq.parity_gates.ZX**0.5)"
```

2021-08-30 18:15 UTC, richrines1 commented on cirq_superstaq/custom_gates_test.py
> +        == "ss.parity_gates.ZXPowGate(exponent=0.5, global_shift=0.123)"
```suggestion
        == "cirq_superstaq.parity_gates.ZXPowGate(exponent=0.5, global_shift=0.123)"
```

2021-08-30 18:15 UTC, richrines1 commented on cirq_superstaq/custom_gates_test.py
> +    assert repr(cirq_superstaq.ZXPowGate()) == "ss.parity_gates.ZX"
```suggestion
    assert repr(cirq_superstaq.ZXPowGate()) == "cirq_superstaq.parity_gates.ZX"
```

2021-08-30 18:29 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    assert repr(cirq_superstaq.ZXPowGate()) == "ss.parity_gates.ZX"
Need to call `assert_equivalent_rerpr`

2021-08-30 19:59 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        e^{-\frac{i}{2} Z \otimes X} = \begin{bmatrix}
What's this `t` for? time? I don't see it on eq 136 on https://arxiv.org/abs/1904.06560

2021-08-30 19:59 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +CR45P = CR ** 0.25
Sounds good. I'll add it on the next commit.

2021-08-30 20:12 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        e^{-\frac{i}{2} Z \otimes X} = \begin{bmatrix}
just realized this should actually be `\frac{i\pi}{2} t`.

it's time in units of the `ZX(pi)` gate time. theta in eq. 136 is equivalent to `pi*t`

2021-08-30 20:29 UTC, richrines1 commented
a check for ZXPowGate should also be added to `custom_resolver()`

2021-08-31 00:15 UTC, singular-value commented on cirq_superstaq/custom_gates.py
> +        e^{-\frac{i}{2} Z \otimes X} = \begin{bmatrix}
ah yeah good point, thanks @richrines1

2021-08-31 00:44 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +CR45P = CR ** 0.25
Added

2021-08-31 00:50 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +CR45P = CR ** 0.25
Actually now that I think about it, do we actually need those variables? That is, are they really that short?

```python
X90 = cirq.rx(np.pi / 2)
RZ = cirq.rz
```

2021-08-31 04:59 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +CR45P = CR ** 0.25
I guess I would lean toward removing CR45[PN] rather than adding the others. They might add clarity when expressing some low-level device-specific applications/decompositions but in that case it seems like they should always be defined locally, not imported. They aren't really useful gates for writing circuits at a higher level

2021-08-31 14:28 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        e^{-\frac{i}{2} Z \otimes X} = \begin{bmatrix}
Done.

2021-08-31 14:28 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +CR45P = CR ** 0.25
I agree. Done.

2021-08-31 15:42 UTC, vtomole commented
> a check for ZXPowGate should also be added to `custom_resolver()`

@richrines1 Done. Please take another look at this PR.

2021-08-31 15:49 UTC, singular-value requested changes

2021-08-31 15:49 UTC, singular-value commented on cirq_superstaq/__init__.py
> +    "CR45P",
```suggestion
```

2021-08-31 16:35 UTC, singular-value reviewed
lgtm, leaving for @richrines1

2021-08-31 17:48 UTC, richrines1 reviewed
lgtm other than some nits and a couple questions.

one other thought (possibly for another PR): would it be useful to define a function like `rzx(theta)` s.t. `rzx(pi) = ZXPowGate(exponent=1)` (similar to `cirq.rx()`, etc.)?

my thinking is that if the circuit is converted to QASM all of the other parameterized gates are normalized around π, so
```
rz(pi*0.5) q[0];
rzx(pi*1.5) q[0],q[1];
```
might be preferable to something like
```
rz(pi*0.5) q[0];
cr(1.5) q[0],q[1];
```
but also might be confusing if `rzx()` isn't something that appears elsewhere

2021-08-31 17:51 UTC, singular-value commented on cirq_superstaq/custom_gates.py
> +CR = ZX = ZXPowGate()  # standard CR is a full turn of ZX, i.e. theta = 180
`CR` is used in our server, but here we could just have `ZX` (and our server can define the `CR` variable)

2021-08-31 17:57 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +class aceCRMinusPlus(aceCR):
It was like that before. The problem is that the resolver couldn't tell the difference between `aceCRPlusMinus` and `aceCRMinusPlus` (the `cirq_type` always ended up being `aceCR`.

2021-08-31 17:58 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +class aceCR(cirq.TwoQubitGate):
Good catch on the capitalization.

2021-08-31 18:23 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +class aceCRMinusPlus(aceCR):
ah - I think that would be fixed by defining `_json_dict_()` for `aceCR`:
```
    def _json_dict_(self) -> Dict[str, Any]:
        return cirq.protocols.obj_to_dict_helper(self, ["polarity"])
```

(and then adding "aceCR" to custom_resolver)

2021-08-31 20:09 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +class aceCRMinusPlus(aceCR):
Nice. That worked. Thanks 👍

2021-08-31 20:11 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +class aceCR(cirq.TwoQubitGate):
Won't follow up on this since we removed the classes due to adding `_json_dict_`

2021-08-31 20:11 UTC, vtomole commented
We can follow up on the qasm namings in qiskit-superstaq.

2021-08-31 20:19 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +class aceCR(cirq.TwoQubitGate):
Actually you are right. Just capitalized.

2021-08-31 20:38 UTC, richrines1 approved these changes
lgtm

2021-08-31 21:03 UTC, merged