Custom gate updates
SupertechLabs/cirq-superstaq pull request #61
Opened 2021-09-29 22:50 UTC by richrines1

* adds `_qasm_` methods to `FermionicSWAPGate`, `ZXPowGate`, and `AceCR`
* adds `_decompose_` to `FermionicSWAPGate`
* adds `rzx(θ)` function for generating exp{-i θ ZX / 2} rotations using a `ZXPowGate` (similar to `cirq.r[xyz]`)
* cleans up multi-line strings in custom_gates_test using `textwrap.dedent`

2021-09-30 16:09 UTC, vtomole requested changes

2021-09-30 16:09 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +            return args.format("zx {0},{1};\n", qubits[0], qubits[1])
How about: 

args.format("zx {0},{1};
", qubits[0], qubits[1])

Also use f-strings: https://realpython.com/python-f-strings/

2021-09-30 16:09 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        return args.format(
f-strings

2021-09-30 16:09 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        return args.format(
f-strings

2021-09-30 16:28 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +            return args.format("zx {0},{1};\n", qubits[0], qubits[1])
unfortunately I don't think f-strings work in this case because args.format is a cirq thing. for example `args.format("zx {0},{1};\n", qubits[0], qubits[1])` produces the QASM:
```
zx q[4],q[5];
```
but if I change it to `args.format(f"zx {qubits[0]}, {qubits[1]};\n")` it becomes:
```
zx 4,5;
```

2021-09-30 18:04 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +            return args.format("zx {0},{1};\n", qubits[0], qubits[1])
fwiw this is how it's defined in `cirq.XPowGate`:
```
def _qasm_(self, args: 'cirq.QasmArgs', qubits: Tuple['cirq.Qid', ...]) -> Optional[str]:
    args.validate_version('2.0')
    if self._exponent == 1 and self._global_shift != -0.5:
        return args.format('x {0};\n', qubits[0])
    elif self._exponent == 0.5:
        return args.format('sx {0};\n', qubits[0])
    return args.format('rx({0:half_turns}) {1};\n', self._exponent, qubits[0])
```

2021-10-01 02:49 UTC, singular-value reviewed
lgtm on skim

2021-10-04 02:17 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +            return args.format("zx {0},{1};\n", qubits[0], qubits[1])
Ah okay thanks.

2021-10-04 02:17 UTC, vtomole approved these changes
LGTM

2021-10-29 18:00 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +    def _decompose_(self, qubits: Tuple[cirq.LineQubit, ...]) -> cirq.OP_TREE:
reverted.

2021-10-29 18:02 UTC, richrines1 commented on cirq_superstaq/custom_gates_test.py
> +    assert gate.__pow__(1.23) is NotImplemented
done (but had to use a `pytest.raises`)

2021-10-29 18:03 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    cirq.testing.assert_pauli_expansion_is_consistent_with_unitary(gate)
Nice. Didn't know this existed.

2021-10-29 18:04 UTC, vtomole commented on cirq_superstaq/custom_gates_test.py
> +    assert gate.__pow__(1.23) is NotImplemented
Ah, accidentally lead to neater code.

2021-10-29 18:04 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +    def _decompose_(self, qubits: Tuple[cirq.Qid, cirq.Qid]) -> cirq.OP_TREE:
Sounds good.

2021-10-29 18:09 UTC, vtomole commented
How are you testing `_apply__unitary_`?

2021-10-29 18:14 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        return NotImplemented
so I guess part of the issue is that (afaik) there's nowhere to import NotImplementedType from (it appears in `types` in python 3.10). cirq has `cirq.type_workarounds.NotImplementedType` but it's just aliased to `Any` which also seems non-ideal..

more here: python/mypy#4791

2021-10-29 18:19 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +from __future__ import annotations
ah it's not necessary, removed.

2021-10-29 18:28 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        return args.format(
I think this would have the same issue as https://github.com/SupertechLabs/cirq-superstaq/pull/61#discussion_r719573359

2021-10-29 18:35 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +            return args.format("zx {0},{1};\n", qubits[0], qubits[1])
Okay, this comment might have gotten lost somewhere. 👍

2021-10-29 18:36 UTC, vtomole commented on cirq_superstaq/custom_gates.py
> +        return NotImplemented
Okay let's use Cirq' method. Pretty non-ideal but it's the best we have..

2021-10-29 18:42 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +        return NotImplemented
done

2021-10-29 21:30 UTC, richrines1 commented
> How are you testing `_apply__unitary_`?

it was implicitly used (to multiply the identity) in `cirq.unitary(cirq.Circuit(operation))`. Added `cirq.testing.assert_has_consistent_apply_unitary` to test it explicitly

2021-10-30 02:48 UTC, singular-value commented on cirq_superstaq/custom_gates.py
> +            return FermionicSWAPGate(exponent * self.theta)
Hmm do we have to restrict the exponents to `(-1, 0, 1)`?
Doesn't L65 also apply for any exponent? (for Fermionic SWAP unitary)

2021-10-30 02:48 UTC, singular-value commented on cirq_superstaq/custom_gates.py
> +    def _decompose_(self, qubits: Tuple[cirq.Qid, cirq.Qid]) -> cirq.OP_TREE:
👍 resolving

2021-10-30 04:09 UTC, richrines1 commented on cirq_superstaq/custom_gates.py
> +            return FermionicSWAPGate(exponent * self.theta)
no unfortunately - for example `fermi(pi/2) ** 2 == iSWAP ** 2 == kron(Z, Z)` but `fermi(pi)` is ~SWAP

2021-10-30 20:44 UTC, singular-value commented on cirq_superstaq/custom_gates.py
> +            return FermionicSWAPGate(exponent * self.theta)
ah yup

2021-10-30 21:23 UTC, singular-value reviewed
(leaving to others to review)

2021-11-01 16:15 UTC, vtomole approved these changes
LGTM

2021-11-01 18:06 UTC, merged