Add comments to cirq_superstaq_example.py
SupertechLabs/cirq-superstaq pull request #7
Opened 2021-08-02 12:47 UTC by rohansk1

Resolves #6

2021-08-02 19:03 UTC, singular-value commented
@rohansk1 is this still a draft PR?

2021-08-03 03:52 UTC, rohansk1 commented
> @rohansk1 is this still a draft PR?

Oops, no

2021-08-04 03:50 UTC, singular-value approved these changes
lgtm

2021-08-04 04:07 UTC, vtomole approved these changes
LGTM

2021-08-06 15:40 UTC, vtomole requested changes

2021-08-06 15:40 UTC, vtomole commented on examples/cirq_superstaq_example.py
>  import cirq
Add doc at top of file as to what this file does. Similar to https://github.com/quantumlib/Cirq/blob/c3f9a5d6d4d539fc9de737e46e9e1d728ef27379/examples/hello_qubit.py#L1

2021-10-01 19:47 UTC, vtomole commented
@dowusu-antwi I've assigned this issue to you.

2021-11-01 15:39 UTC, vtomole commented on examples/cirq_superstaq_example.py
> +=== EXAMPLE OUTPUT ===
This is different from the actual output of the program here. 

- We don't print the circuit
-  I don't see `output=1100011010111001...1101` when i run this.

2021-11-01 18:25 UTC, vtomole commented on examples/cirq_superstaq_example.py
> +=== EXAMPLE OUTPUT ===
Add `print("This is the job that's created: ", job.status())` as well.

2021-11-01 18:36 UTC, dowusu-antwi commented on examples/cirq_superstaq_example.py
> +=== EXAMPLE OUTPUT ===
Done.

2021-11-01 18:48 UTC, vtomole approved these changes
LGTM

2021-11-01 18:50 UTC, merged