include aqt compilation functionality in cirq-superstaq
SupertechLabs/cirq-superstaq pull request #8
Opened 2021-08-02 18:20 UTC by singular-value

2021-08-02 18:37 UTC, vtomole requested changes

2021-08-02 18:37 UTC, vtomole commented on cirq_superstaq/applications.py
> +import cirq_superstaq as css
I'll always bring this up: I'm uneasy about abbreviating imports like this. I feel like your package has to be "popular" enough to warrant this. For example, people know that `np` is numpy. They don't need to find where the import is stated to find this out.

2021-08-02 18:37 UTC, vtomole commented on cirq_superstaq/job_test.py
> +import cirq_superstaq as superstaq
Let's revert this to `import cirq_superstaq` to discourage doing imports like this. In a situation where I import `cirq_superstaq` and `qiksit_superstaq` in the same file, which one deserves the `as superstaq` abbreviation?

2021-08-02 18:37 UTC, vtomole commented on cirq_superstaq/superstaq_client_test.py
> +import cirq_superstaq as superstaq
Revert to `import cirq_superstaq`

2021-08-02 18:37 UTC, vtomole commented on cirq_superstaq/applications_test.py
> +def test__get_api_url() -> None:
```suggestion
def test_get_api_url() -> None:
```

2021-08-02 18:37 UTC, vtomole commented on cirq_superstaq/applications_test.py
> +def test__get_headers() -> None:
```suggestion
def test_get_headers() -> None:
```

2021-08-02 18:37 UTC, vtomole commented on cirq_superstaq/applications_test.py
> +def test__should_verify_requests() -> None:
```suggestion
def test_should_verify_requests() -> None:
```

2021-08-02 18:37 UTC, vtomole commented on cirq_superstaq/applications.py
> +import json
The code in this file would be more appropriate in `superstaq_client.py` instead of `applications.py`.

2021-08-02 18:43 UTC, singular-value commented on cirq_superstaq/applications.py
> +import cirq_superstaq as css
Oh yeah, I meant to revert this. I'm going to do `css` in shell, but I agree that to look more like typical cirq code, we should do `from cirq_superstaq import blah` instead

2021-08-02 18:46 UTC, singular-value commented on cirq_superstaq/job_test.py
> +import cirq_superstaq as superstaq
Sure.
(To be clear, this was in the previous code-->I was just re-ordering to comply with my change to .flake8 where cirq_superstaq is now considered a local module)

2021-08-02 18:49 UTC, singular-value commented on cirq_superstaq/applications.py
> +import json
I agree medium-term, when we have a `/compile` endpoint as opposed to an aqt-specific compilation endpoint.

I see applications.py being fairly specific use cases, whereas superstaq_client.py being "cirq-general" use cases.

2021-08-02 18:55 UTC, vtomole commented on cirq_superstaq/applications.py
> +import json
How about renaming to `aqt.py`? That way we don't have finance, logistic, and finance stuff in the same file.

2021-08-02 18:58 UTC, singular-value commented on cirq_superstaq/applications.py
> +import json
Makes sense.
cc @pnoell, you'll want to put your stuff in finance.py and logistics.py --> I'm going to get rid of applications.py

2021-08-02 19:00 UTC, pnoell commented on cirq_superstaq/applications.py
> +import json
Sounds good, should I copy over the files? Or is there a way to mirror them from the SuperstaQ repo?

2021-08-02 19:02 UTC, singular-value commented on cirq_superstaq/applications.py
> +import json
@vtomole thoughts on where you think `_get_api_url()`, `_get_headers()`, and `_should_verify_requests()` should go?

I realize I put aqt_compile into applications.py because I wanted to have those three functions available throughout superstaq for any applications.


One idea is to move them into _init_vars.py

2021-08-02 19:08 UTC, singular-value commented on cirq_superstaq/applications.py
> +import json
> Sounds good, should I copy over the files? Or is there a way to mirror them from the SuperstaQ repo?

@pnoell so the logistics.py and finance.py files can stay in SuperstaQ, but in this repository, you can make two new files called logistics.py and finance.py-->those should be very "thin" files, basically just things like

```
def tsp(locs):
    code for making a POST request to the /tsp endpoint
```

2021-08-02 19:11 UTC, vtomole commented on cirq_superstaq/applications.py
> +import json
Before we discus that, this is how i'm seeing people using `aqt_compile`

```python
import cirq
import cirq_superstaq


q0 = cirq.LineQubit(0)
q1 = cirq.LineQubit(1)

circuit = cirq.Circuit(cirq.H(q0), cirq.CNOT(q0, q1), cirq.measure(q0))


service = cirq_superstaq.Service(
    api_key="""Insert superstaq token that you received from https://superstaq.super.tech""",
    verbose=True,
)

aqt_compiled_circuit = service.aqt_compile(circuit=circuit)
```

Does this look correct to you?

2021-08-02 20:14 UTC, singular-value commented on cirq_superstaq/applications.py
> +import json
Almost, except I don't see `service` as providing a specific `aqt_compile()` method but rather a general `compile` method:

```py
import cirq
import cirq_superstaq

q0 = cirq.LineQubit(0)
q1 = cirq.LineQubit(1)

circuit = cirq.Circuit(cirq.H(q0), cirq.CNOT(q0, q1), cirq.measure(q0))

service = cirq_superstaq.Service(
    api_key="""Insert superstaq token that you received from https://superstaq.super.tech""",
    verbose=True,
)

aqt_compiled_circuit = service.compile(circuit=circuit, target="aqt")
honeywell_compiled_circuit = service.compile(circuit=circuit, target="honeywell")
```

But we're not quite ready for providing that API yet-->hence why I was viewing `aqt_compile` as a specific application, not so far unlike finance or logistics.

2021-08-02 20:24 UTC, vtomole commented on cirq_superstaq/applications.py
> +import json
Let's add a `service.compile` that throws an error when the target that is not `aqt`

2021-08-05 22:13 UTC, singular-value commented on cirq_superstaq/superstaq_client_test.py
> +import cirq_superstaq as superstaq
resolved

2021-08-05 22:13 UTC, singular-value commented on cirq_superstaq/job_test.py
> +import cirq_superstaq as superstaq
resolved

2021-08-05 22:13 UTC, singular-value commented on cirq_superstaq/applications_test.py
> +def test__get_api_url() -> None:
resolved

2021-08-05 22:14 UTC, singular-value commented on cirq_superstaq/applications_test.py
> +def test__should_verify_requests() -> None:
no longer relevant

2021-08-05 22:14 UTC, singular-value commented on cirq_superstaq/applications.py
> +import json
discussed in person

2021-08-06 16:07 UTC, vtomole requested changes

2021-08-06 16:07 UTC, vtomole commented on setup.py
> +# Optional installations. For example, pip install cirq-superstaq[aqt] will include
When I suggested this I was more thinking along the lines of having the `aqt.py` as a module that wouldn't be installed by default; but I don't think it's worth the amount of labor it's going to take messing around with Python's import system. 

Thoughts?

2021-08-06 16:07 UTC, vtomole commented on cirq_superstaq/job_test.py
> +import cirq_superstaq as superstaq
👍

2021-08-06 16:22 UTC, singular-value commented on cirq_superstaq/aqt.py
> +    if True:  # pragma: no cover b/c qtrl is not yet open source
so that only one `# pragma: no cover` is needed

2021-08-06 16:23 UTC, singular-value commented on cirq_superstaq/aqt.py
> +        return (out_circuit, seq)
👍

2021-08-06 16:47 UTC, vtomole commented on cirq_superstaq/aqt.py
> +    if True:  # pragma: no cover b/c qtrl is not yet open source
👍

2021-08-06 19:46 UTC, singular-value commented on cirq_superstaq/aqt.py
> +    """Reads out returned JSON from SuperstaQ API's AQT compilation endpoint.
Done

2021-08-06 19:47 UTC, singular-value commented on setup.py
> +# Optional installations. For example, pip install cirq-superstaq[aqt] will include
Agreed. Went back to original setup.py (minus a print statement)

2021-08-06 19:47 UTC, singular-value commented on cirq_superstaq/aqt.py
> +    pass
(this is needed for the type in L17)

2021-08-06 19:55 UTC, vtomole commented on cirq_superstaq/aqt.py
> +try:
Is this added just for the future or is it to make mypy happy?

2021-08-06 20:07 UTC, singular-value commented on cirq_superstaq/aqt.py
> +try:
it's to make mypy happy

2021-08-06 20:10 UTC, vtomole commented on cirq_superstaq/aqt.py
> +    pass
👍

2021-08-06 20:10 UTC, vtomole commented on cirq_superstaq/aqt.py
> +try:
👍

2021-08-06 20:10 UTC, vtomole approved these changes
LGTM

2021-08-06 20:16 UTC, merged