Deserialize circuits to always returns list
SupertechLabs/cirq-superstaq pull request #89
Opened 2021-10-13 18:55 UTC by richrines1

this makes it symmetric with `qiskit_superstaq.serialization.deserialize_circuits()` (which uses `qpy_serialization.load()` which always returns a list of circuits). It also simplifies type checking a bit

2021-10-13 21:07 UTC, vtomole commented on cirq_superstaq/aqt.py
> +        cirq_superstaq.serialization.deserialize_circuits(c)[0] for c in json_dict["cirq_circuits"]
What happens when we do

```python
compiled_circuits = cirq_superstaq.serialization.deserialize_circuits(json_dict["cirq_circuits"])
```

2021-10-14 00:20 UTC, vtomole commented on cirq_superstaq/aqt.py
> +        cirq_superstaq.serialization.deserialize_circuits(c)[0] for c in json_dict["cirq_circuits"]
👍

2021-10-14 00:21 UTC, vtomole requested changes
Let's put all the client changes related to the API on hold until we update the API.

2021-10-16 06:59 UTC, richrines1 commented
this was absorbed into #83. closing.

2021-10-16 06:59 UTC, closed without merging